repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: reorder-python-imports
        name: Reorder python imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=src]
